name: Compile idevicerestore
on: [push]
jobs:
  linux-limd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh limd

      - name: Zip libimobiledevice
        run: zip -r libimobiledevice_linux.zip bin/libimobiledevice/

      - name: Update latest release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: libimobiledevice_linux.zip
