name: Compile idevicerestore
on: [push]
jobs:
  linux-limd:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: linux-limd-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh limd

      - name: Zip libimobiledevice
        run: zip -r libimobiledevice_linux-${{ matrix.arch.name }}.zip bin/

      - name: Update latest release
        uses: pyTooling/Actions/releaser/composite@main
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: libimobiledevice_linux-${{ matrix.arch.name }}.zip

  # win:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: MINGW64
  #         update: true
  #
  #     - name: Run compile script
  #       run: ./compile.sh
  #
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: idevicerestore_win
  #         path: bin/
