name: Compile idevicerestore
on: [push]
jobs:
  linux-idr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh

      - uses: actions/upload-artifact@v3
        with:
          files: idevicerestore_linux
          path: bin/

  linux-limd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh limd

      - uses: actions/upload-artifact@v3
        with:
          files: libimobiledevice_linux
          path: bin/
